name: Sync Spotify Playlists to Qobuz

on:
  schedule:
    - cron: '0 12 * * 1'  # 毎週月曜日12:00に実行（統合プレイリスト更新後）
  workflow_dispatch:     # 手動実行もできるようにする

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy selenium webdriver-manager
      
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Run sync script
        run: python sync_playlists.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_AUTH_CACHE: ${{ secrets.SPOTIFY_AUTH_CACHE }}
          DISCOVER_WEEKLY_ID: ${{ secrets.DISCOVER_WEEKLY_ID }}
          QOBUZ_EMAIL: ${{ secrets.QOBUZ_EMAIL }}
          QOBUZ_PASSWORD: ${{ secrets.QOBUZ_PASSWORD }}
